apiVersion: v1

kind: ConfigMap

metadata:

  name: fe-api-config

data:

  HNG_LESSON_DAY: day5

  HNG_API_ORIGINS: https://hng.idimma.com

  HNG_API_HOST: 0.0.0.0

  HNG_API_PORT: 8000

  HNG_API_URL: https://api.hng.idimma.com 
